global:
  scrape_interval: 15s # Intervalo padrão de coleta de métricas para todos os jobs

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mysqld_exporter"
    static_configs:
      - targets: ["mysqld_exporter:9104"]
